---
title: "Modeling the Effects of Nutrition with Mixed-Effect Bayesian Network"
author: "Jari Turkia"
output: 
  md_document:
    variant: markdown_github
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Modeling the Effects of Nutrition with Mixed-Effect Bayesian Network

This work proposes Mixed-Effect Bayesian Network (MEBN) as a method for modeling the effects of nutrition. It allows to identify both typical and personal correlations between nutrients and their bodily responses. Predicting a personal network of nutritional reactions would allow interesting applications at personal diets and in understanding this complex system. Brief theory of MEBN is given followed by implementation in R and Stan. A real life dataset from a nutritional Sysdimet study is then analyzed with the method and the results are visualized with an interactive JavaScript-visualization.

[View HTML-version of the notebook here](http://htmlpreview.github.io/?https://github.com/turkiaj/StanCon2018/blob/master/PersonalEffectsOfNutrition.html)


## Contents

Main body of the presentation is found here as fully functional RMarkdown notebook, and also HTML and PDF renderitions of it. The notebook uses my R-package "MEBN" for constructing a Mixed-Effect Bayesian Network that models the effects of nutrition from a real life nutritional dataset. The fully Bayesian estimation of the local mixed-effect models at the network is done with Stan. Visualization of the network is created with JavaScript library sigma.js and some customizations of it.

- PersonalEffectsOfNutrition.Rmd : RMarkdown notebook
- PersonalEffectsOfNutrition.html : HTML knit of the notebook with active JavaScript visualization
- PersonalEffectsOfNutrition.pdf : PDF knit of the notebook
- population_graph.htm : HTML document for graph visualization
- biblio.bib : References for the notebook in BibLatex format
- data-folder: The dataset that is used in the notebook analysis
- Data description.xlsx : Excel file that describes the metadata for analyzed dataset
- mebn-folder: The R-code for constructing MEBN and stan-model definitions
- visualization-folder: JavaScript code for graph visualization
- models-folder: Sampled Stan-models are cached in this folder once the notebook is executed. It is empty by default.

## License

Material in this repository is licensed under CC 4.0
https://creativecommons.org/licenses/by/4.0/

## Requirements

Besides working installation of Stan, following R-packages are required for this notebook to execute correctly.

Use install_packages.r script to install.

** Session Info **

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252   
[3] LC_MONETARY=Finnish_Finland.1252 LC_NUMERIC=C                    
[5] LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2         bayesplot_1.4.0      rgexf_0.15.3        
 [4] Rook_1.1-1           XML_3.98-1.9         rstan_2.17.2        
 [7] StanHeaders_2.17.1   ggplot2_2.2.1        igraph_1.1.2        
[10] xlsx_0.5.7           xlsxjars_0.6.1       rJava_0.9-9         
[13] knitr_1.18           RevoUtils_10.0.7     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     bindr_0.1        pillar_1.0.1     compiler_3.4.3  
 [5] plyr_1.8.4       tools_3.4.3      digest_0.6.13    tibble_1.4.1    
 [9] gtable_0.2.0     pkgconfig_2.0.1  rlang_0.1.6      yaml_2.1.16     
[13] parallel_3.4.3   gridExtra_2.3    dplyr_0.7.4      stats4_3.4.3    
[17] grid_3.4.3       glue_1.2.0       inline_0.3.14    R6_2.2.2        
[21] magrittr_1.5     scales_0.5.0     htmltools_0.3.6  assertthat_0.2.0
[25] colorspace_1.3-2 labeling_0.3     brew_1.0-6       lazyeval_0.2.1  
[29] munsell_0.4.3 


